using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Linq;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Threading;
using System.Net.Http.Headers;

namespace Storage.Generators
{
    [Generator]
    public sealed class BinarySerializerGenerator : IIncrementalGenerator
    {
        private static readonly DiagnosticDescriptor UnsupportedPropertyType = new(
            id: "BSG001",   //  сокращение от Binary Serializer Generator, сделал своё инфо об ошибке 
            title: "Неподдерживаемый тип свойства",
            messageFormat: "Свойство '{0}' имеет неподдерживаемый тип '{1}'",
            category: "BinarySerialization",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);


        public void Initialize (IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(
                    static output =>
                    {
                        const string source = """
                            // <auto-generated/>

                            namespace Storage.Serialization
                            {
                                [System.AttributeUsage(
                                    System.AttributeTargets.Class,
                                    AllowMultiple = false,
                                    Inherited = false)]
                                public sealed class GenerateBinarySerializerAttribute
                                    : System.Attribute
                                {
                                }
                            }
                        """;

                        output.AddSource("GenerateBinarySerializerAttribute.g.cs", SourceText.From(source, Encoding.UTF8));
                    }
                );

            var classes = context.SyntaxProvider.ForAttributeWithMetadataName(
                    fullyQualifiedMetadataName: "Storage.Serialization.GenerateBinarySerializerAttribute",
                    predicate: static(node, cancellationToken) => node is ClassDeclarationSyntax,
                    transform: static(attributeContext, cancellationToken) => (INamedTypeSymbol)attributeContext.TargetSymbol
                );

            context.RegisterSourceOutput(
                    classes,
                    static(output, classSymbol) => 
                        {
                            GenerateSerializer(output, classSymbol);
                            //GeneratePropertyReport(output, classSymbol);
                        }
                );

        }

        public static void GenerateSerializer(SourceProductionContext output, INamedTypeSymbol classSymbol)
        {
            var properties = classSymbol
                    .GetMembers()      //   свойства, методы, поля
                    .OfType<IPropertySymbol>()  //  оставляет только свойства
                    .Where(static property =>
                            property.DeclaredAccessibility == Accessibility.Public &&   //  само свойство публичное
                            !property.IsStatic &&   //  без статических свойств
                            !property.IsIndexer &&  //   без индексаторов
                            property.GetMethod is not null &&   //  у свойства есть getter
                            property.GetMethod.DeclaredAccessibility == Accessibility.Public)   //  getter публичный
                    .OrderBy(static property => property.Name, System.StringComparer.Ordinal)
                    .ToArray();

            foreach (var property in properties)
            {
                SpecialType type = property.Type.SpecialType;

                if (type != SpecialType.System_Int32 && type != SpecialType.System_String && type != SpecialType.System_DateTime)
                {
                    output.ReportDiagnostic(
                        Diagnostic.Create(
                            UnsupportedPropertyType,
                            property.Locations.FirstOrDefault(),
                            property.Name,
                            property.Type.ToDisplayString()
                        )
                    );

                    return;
                }

            }

            var source = new StringBuilder();

            source.AppendLine("// <auto-generated/>");
            source.AppendLine("#nullable enable");

            bool hasNamespace = !classSymbol.ContainingNamespace.IsGlobalNamespace;

            if (hasNamespace)
            {
                source.AppendLine($"namespace {classSymbol.ContainingNamespace.ToDisplayString()}");
                source.AppendLine("{");
            }

            source.AppendLine($"public partial class @{classSymbol.Name}");
            source.AppendLine("{");

            source.AppendLine("    public void SerializeToBinary(global::System.IO.Stream stream)");
            source.AppendLine("    {");

            source.AppendLine("        using var writer = new global::System.IO.BinaryWriter(");
            source.AppendLine("            stream, global::System.Text.Encoding.UTF8, leaveOpen: true);");

            foreach (var property in properties)
            {
                string access = $"this.@{property.Name}";

                switch (property.Type.SpecialType)
                {
                    case SpecialType.System_Int32:
                        source.AppendLine($"        writer.Write({access});");
                        break;

                    case SpecialType.System_DateTime:
                        source.AppendLine($"        writer.Write({access}.ToBinary());");
                        break;

                    case SpecialType.System_String:
                        source.AppendLine("        {");
                        source.AppendLine($"            var value = {access};");
                        source.AppendLine("            writer.Write(value is not null);");
                        source.AppendLine("            if (value is not null)");
                        source.AppendLine("            {");
                        source.AppendLine("                writer.Write(value);");
                        source.AppendLine("            }");
                        source.AppendLine("        }");
                        break;
                }
            }

            source.AppendLine("    }");

            AppendDeserializer(source, classSymbol, properties);

            AppendArraySerializer(source, properties);

            source.AppendLine("}");

            if (hasNamespace)
            {
                source.AppendLine("}");
            }

            output.AddSource($"{classSymbol.ToDisplayString()}.BinarySerializer.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));

        }

        public static void AppendDeserializer(StringBuilder source, INamedTypeSymbol classSymbol, IPropertySymbol[] properties)
        {
            source.AppendLine();

            source.AppendLine($"    public static @{classSymbol.Name} DeserializeFromBinary(");
            source.AppendLine("        global::System.IO.Stream stream)");
            source.AppendLine("    {");

            source.AppendLine("        using var reader = new global::System.IO.BinaryReader(");
            source.AppendLine("            stream, global::System.Text.Encoding.UTF8, leaveOpen: true);");

            source.AppendLine();
            source.AppendLine($"        return new @{classSymbol.Name}");
            source.AppendLine("        {");

            foreach (var property in properties)
            {
                string readExpression;

                switch (property.Type.SpecialType)
                {
                    case SpecialType.System_Int32: 
                        readExpression = "reader.ReadInt32()";
                        break;

                    case SpecialType.System_DateTime:
                        readExpression = "global::System.DateTime.FromBinary(reader.ReadInt64())";
                        break;

                    case SpecialType.System_String:
                        readExpression = "reader.ReadBoolean() ? reader.ReadString() : null!";
                        break;

                    default:
                        throw new System.InvalidOperationException($"Неподдерживаемый тип: {property.Type}");   //  типы уже проверены в GenerateSerializer
                }

                source.AppendLine($"            @{property.Name} = {readExpression},");

            }

            source.AppendLine("        };");
            source.AppendLine("    }");
        }

        private static void AppendArraySerializer(StringBuilder source, IPropertySymbol[] properties)
        {
            source.AppendLine();
            source.AppendLine("    public byte[] SerializeToBinary()");
            source.AppendLine("    {");

            //  cохраняем значения свойств в локальные переменные
            for (int i = 0; i < properties.Length; i++)
            {
                source.AppendLine($"        var value{i} = this.@{properties[i].Name};");
            }

            source.AppendLine();
            source.AppendLine("        int size = 0;");

            //  рассчитываем размер
            for (int i = 0; i < properties.Length; i++)
            {
                switch (properties[i].Type.SpecialType)
                {
                    case SpecialType.System_Int32:
                        source.AppendLine("        size = checked(size + 4);");
                        break;

                    case SpecialType.System_DateTime:
                        source.AppendLine("        size = checked(size + 8);");
                        break;

                    case SpecialType.System_String:
                        source.AppendLine($"        int byteCount{i} = value{i} is null");
                        source.AppendLine("            ? 0");
                        source.AppendLine($"            : global::System.Text.Encoding.UTF8.GetByteCount(value{i});");

                        //  один байт признак наличия строки
                        source.AppendLine("        size = checked(size + 1);");

                        source.AppendLine($"        if (value{i} is not null)");
                        source.AppendLine("        {");

                        //  байты строки плюс минимум один байт длины
                        source.AppendLine($"            size = checked(size + byteCount{i} + 1);");

                        //  учитываем дополнительные байты длины строки
                        source.AppendLine($"            for (int remaining = byteCount{i}; remaining >= 128; remaining >>= 7)");
                        source.AppendLine("            {");
                        source.AppendLine("                size = checked(size + 1);");
                        source.AppendLine("            }");

                        source.AppendLine("        }");
                        break;
                }
            }

            //  единственный массив, содержащий готовый результат
            source.AppendLine();
            source.AppendLine("        byte[] bytes = new byte[size];");
            source.AppendLine("        global::System.Span<byte> destination = bytes;");
            source.AppendLine("        int offset = 0;");
            source.AppendLine();

            //  записываем значения в массив
            for (int i = 0; i < properties.Length; i++)
            {
                switch (properties[i].Type.SpecialType)
                {
                    case SpecialType.System_Int32:
                        source.AppendLine("        global::System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian(");
                        source.AppendLine($"            destination.Slice(offset, 4), value{i});");
                        source.AppendLine("        offset += 4;");
                        break;

                    case SpecialType.System_DateTime:
                        source.AppendLine("        global::System.Buffers.Binary.BinaryPrimitives.WriteInt64LittleEndian(");
                        source.AppendLine($"            destination.Slice(offset, 8), value{i}.ToBinary());");
                        source.AppendLine("        offset += 8;");
                        break;

                    case SpecialType.System_String:
                        source.AppendLine($"        destination[offset++] = value{i} is null ? (byte)0 : (byte)1;");

                        source.AppendLine($"        if (value{i} is not null)");
                        source.AppendLine("        {");

                        //  записываем длину строки порциями по 7 бит
                        source.AppendLine($"            uint remaining = (uint)byteCount{i};");

                        source.AppendLine("            while (remaining >= 128)");
                        source.AppendLine("            {");
                        source.AppendLine("                destination[offset++] = (byte)((remaining & 0x7Fu) | 0x80u);");
                        source.AppendLine("                remaining >>= 7;");
                        source.AppendLine("            }");

                        source.AppendLine("            destination[offset++] = (byte)remaining;");

                        //  кодируем строку сразу в итоговый массив
                        source.AppendLine("            offset += global::System.Text.Encoding.UTF8.GetBytes(");
                        source.AppendLine($"                global::System.MemoryExtensions.AsSpan(value{i}),");
                        source.AppendLine($"                destination.Slice(offset, byteCount{i}));");

                        source.AppendLine("        }");
                        break;
                }
            }

            source.AppendLine();
            source.AppendLine("        return bytes;");
            source.AppendLine("    }");
        }


        public static void GeneratePropertyReport(SourceProductionContext output, INamedTypeSymbol classSymbol)
        {
            var properties = classSymbol
                    .GetMembers()      //   свойства, методы, поля
                    .OfType<IPropertySymbol>()  //  оставляет только свойства
                    .Where(static property =>
                            property.DeclaredAccessibility == Accessibility.Public &&   //  само свойство публичное
                            !property.IsStatic &&   //  без статических свойств
                            !property.IsIndexer &&  //   без индексаторов
                            property.GetMethod is not null &&   //  у свойства есть getter
                            property.GetMethod.DeclaredAccessibility == Accessibility.Public)   //  getter публичный
                    .OrderBy(static property => property.Name, System.StringComparer.Ordinal)
                    .ToArray();

            var source = new StringBuilder();

            source.AppendLine("// <auto-generated/>");
            source.AppendLine($"// Найден класс: {classSymbol.ToDisplayString()}");
            source.AppendLine($"// Публичных читаемых свойств: {properties.Length}");

            //  добавляется строка для каждого свойства
            foreach (var property in properties)
            {
                source.AppendLine($"// {property.Name}: {property.Type.ToDisplayString()}");
            }

            //  roslyn будет различать сгенерированные исходники
            string hintName = $"{classSymbol.ToDisplayString()}.Properties.g.cs";

            output.AddSource(hintName, SourceText.From(source.ToString(), Encoding.UTF8));
        }

    }
}
